# Generated by Django 3.2.5 on 2021-09-03 14:35

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Fist name', max_length=32)),
                ('last_name', models.CharField(help_text='Last name', max_length=32)),
                ('email', models.EmailField(help_text='E-mail', max_length=254)),
                ('phone_number', phone_field.models.PhoneField(blank=True, help_text='Phone number', max_length=31)),
                ('admin_role', models.BooleanField(default=False)),
            ],
        ),
    ]
