# Generated by Django 3.2.5 on 2021-09-03 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team_member', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='picture',
            field=models.ImageField(blank=True, upload_to='profile_pictures'),
        ),
    ]
